import { Service } from '@angular/core';

export interface Category {
  id: string;
  icon: string;
  title: string;
  color: string;
  bg: string;
  questions: string[];
}

@Service()
export class QuestionService {
  private categories: Category[] = [
    {
      id: 'typescript',
      icon: 'ti-brand-typescript',
      title: 'TypeScript',
      color: '#185FA5',
      bg: '#E6F1FB',
      questions: [
        'Difference between Type and Interface',
        'What are Generics in TypeScript?',
        'What is the latest JavaScript version you have used?',
        'Do you have exposure working in Vanilla JavaScript?',
        'What are ES6 features?',
      ],
    },
    {
      id: 'javascript-fundamentals',
      icon: 'ti-brand-javascript',
      title: 'JavaScript Fundamentals',
      color: '#B45309',
      bg: '#FEF3E2',
      questions: [
        'Debounce vs Throttle',
        'Explain how the JavaScript Event Loop works',
        'Difference between var, let, and const',
        'Explain closures with practical examples',
        'What is currying in JavaScript?',
        'Difference between == and ===',
        'Deep copy vs shallow copy',
      ],
    },
    {
      id: 'signals',
      icon: 'ti-bolt',
      title: 'Signals & Reactivity',
      color: '#3B6D11',
      bg: '#EAF3DE',
      questions: [
        'What are Signals in Angular?',
        'Difference between Computed Signal and Effect',
        'Difference between Signals and BehaviorSubject',
        'Have you used BehaviorSubject in any real scenario?',
        'Difference between Subject, BehaviorSubject, and ReplaySubject in RxJS',
        'Signals vs NgRx',
        'Difference between Signals and RxJS',
        'When would you choose Signals over Observables?',
      ],
    },
    {
      id: 'change-detection',
      icon: 'ti-refresh',
      title: 'Change Detection',
      color: '#854F0B',
      bg: '#FAEEDA',
      questions: [
        'How does Change Detection work in Angular?',
        'Difference between Default and OnPush Change Detection Strategy',
        'How does Angular detect changes in a zone-less environment?',
        'Difference between markForCheck() and detectChanges()',
      ],
    },
    {
      id: 'rxjs',
      icon: 'ti-waves',
      title: 'RxJS & Observables',
      color: '#534AB7',
      bg: '#EEEDFE',
      questions: [
        'Which RxJS operators have you used?',
        'How to handle errors and retry an API call up to 3 times using RxJS?',
        'Should error handling happen before or after subscribing?',
        'Explain the complete RxJS flow: API response, subscribe, and error handling',
        'Why do we use pipe() before subscribing?',
        'What does the map operator do?',
        'What does the filter operator do?',
        'Difference between switchMap and mergeMap',
        'Why do we use Observables in Angular?',
        'What is the difference between Subject, BehaviorSubject, ReplaySubject, and AsyncSubject?',
        'Explain the difference between cold and hot observables with examples',
        'When would you use switchMap vs mergeMap vs concatMap vs exhaustMap? Give a real-world scenario for each',
        'What does shareReplay(1) do and when is it essential?',
        'Explain the difference between combineLatest, forkJoin, zip, and withLatestFrom',
        'What is takeUntil and how is it used for subscription management? What are modern alternatives?',
        'What is the difference between debounceTime and throttleTime?',
        'How does scan differ from reduce? Where would you use scan in an Angular app?',
        'What are schedulers in RxJS and when would you use asyncScheduler vs queueScheduler?',
        'How do you handle errors in RxJS streams? Explain catchError, retry, and retryWhen',
        "You're building a type-ahead search — implement it using RxJS operators, handling debounce, cancellation of in-flight requests, and deduplication",
        'You have a payment form where the user clicks Submit. How do you prevent duplicate submissions using RxJS? Which operator do you choose and why?',
        'An observable chain emits an error and the entire stream terminates. How do you architect a resilient stream that recovers gracefully?',
        "You need to poll an API every 10 seconds but stop polling when the component is destroyed. Show how you'd implement this",
      ],
    },
    {
      id: 'scenario-based',
      icon: 'ti-bulb',
      title: 'Scenario-Based Questions',
      color: '#0E7490',
      bg: '#E0F7FA',
      questions: [
        'How do you prevent duplicate API requests in Angular?',
        'A user clicks a button 10 times and 10 API calls are triggered. How would you handle this using RxJS?',
        'An API response is required by multiple components. How would you avoid repeated API calls?',
      ],
    },
    {
      id: 'components',
      icon: 'ti-layout-2',
      title: 'Components & Templates',
      color: '#0F6E56',
      bg: '#E1F5EE',
      questions: [
        'Explain Angular lifecycle hooks',
        'What is the purpose of ngOnInit() in Angular components?',
        'Content projection and ViewChild',
        'How to use BComponent inside AComponent?',
        'What is ViewEncapsulation?',
        'If I want to toggle an element dynamically without using *ngIf, how?',
        'If I want to change CSS dynamically, how?',
        'Is ngClass the only way to change CSS dynamically?',
        'Difference between ng-content and ng-template',
        'What are Standalone Components and their advantages?',
      ],
    },
    {
      id: 'directives',
      icon: 'ti-code',
      title: 'Directives & Decorators',
      color: '#993C1D',
      bg: '#FAECE7',
      questions: [
        'What are directives in Angular?',
        'Create a custom directive to change background color on hover/unhover',
        'What does @HostListener do?',
      ],
    },
    {
      id: 'forms',
      icon: 'ti-forms',
      title: 'Forms',
      color: '#993556',
      bg: '#FBEAF0',
      questions: [
        'What can Reactive Forms do in a real-time application?',
        'How to implement Dynamic Forms in Angular using FormArray?',
        'What is setControl in FormArray?',
        'Difference between setValue and patchValue',
        'How to implement a dynamic form where input fields are shown/hidden based on selection?',
      ],
    },
    {
      id: 'routing',
      icon: 'ti-route',
      title: 'Routing & Guards',
      color: '#185FA5',
      bg: '#E6F1FB',
      questions: [
        'What are route guards?',
        'Difference between canMatch and canLoad',
        'What are Resolvers?',
        'Is it possible to use multiple Router Outlets in Angular? If yes, how?',
        'How to implement Page Not Found route?',
        'How to set query parameters?',
        'How to implement lazy loading in Angular?',
        'Explain Lazy Loading and Preloading Strategies',
        'How can you restrict routes based on user in Angular?',
      ],
    },
    {
      id: 'state-architecture',
      icon: 'ti-topology-star',
      title: 'State Management & Architecture',
      color: '#534AB7',
      bg: '#EEEDFE',
      questions: [
        'What is NgRx and how did you implement it in Angular applications?',
        'What are Interceptors?',
        'How to write an HTTP interceptor to handle common error responses?',
        'Different ways to share data between components',
        'In a large Angular application, how do you pass data between components?',
        'If multiple applications need to share data, how would you design the communication?',
        'If admin updates data and changes need to reflect in multiple components simultaneously, how?',
        'What is Multi Provider Token?',
        'What is Dependency Injection in Angular apart from injecting services?',
        'Why do we use services in Angular apart from API calls?',
        'How to implement SOLID principles in an Angular application?',
        'Have you worked on Micro Frontend architecture?',
        'How does the browser load an Angular application?',
        'How does Dependency Injection work internally?',
        'Explain the NgRx data flow: Action → Reducer → Store → Selector → Component → Effect → Action',
        'What is the difference between createAction, createReducer, and createEffect?',
        'What are Selectors in NgRx? Explain memoization and why it matters for performance',
        'What is createFeatureSelector and when do you use it?',
        'How do Effects work in NgRx? Explain ofType, switchMap, and error handling inside effects',
        'What is NgRx Entity and what problem does it solve?',
        'What is the NgRx Signal Store (introduced in NgRx 17)? How does it differ from the traditional store?',
        'Explain concatLatestFrom (formerly withLatestFrom in effects) and its use case',
        'How would you implement optimistic updates using NgRx?',
        'What is the difference between dispatch and select in NgRx? How do you avoid unnecessary re-renders via selectors?',
        'Design the NgRx state shape for a banking dashboard that shows account list, selected account details, and transaction history with pagination',
        'An Effect makes an HTTP call, but you want to cancel the previous request if a new action arrives. Which operator do you use inside the effect and why?',
        'Your selector is being called too frequently causing performance issues. How do you diagnose and fix this?',
        'How would you implement undo/redo functionality using NgRx?',
      ],
    },
    {
      id: 'performance-testing',
      icon: 'ti-speedboat',
      title: 'Performance, Testing & Tooling',
      color: '#3B6D11',
      bg: '#EAF3DE',
      questions: [
        'What are ways to optimize an Angular application?',
        'Handle bulk records using virtual scrolling and pagination, and limit API result per page',
        'Global error handling vs component-level error handling',
        'What is Server-Side Rendering (SSR) and Client-Side Rendering (CSR)?',
        'How will you mock a service?',
        'Have you used Angular testing frameworks?',
        'What deployment activities have you handled?',
        'Have you worked on CI/CD pipelines?',
        'Have you worked on resolving issues in CI/CD pipelines?',
        'Have you used any AI tools?',
        'Difference between Ask, Agent, and Plan mode in GitHub Copilot',
        'What are new features of Angular 21?',
        'Which Angular versions have you worked on?',
        'Remove duplicate elements from an array [1,2,2,3,4,4,5] using built-in method and for loop',
        'Why did you choose Angular when most developers are learning React?',
        'What is Flexbox?',
        'DOM manipulations',
        'What is your understanding of the DOM? Explain with a real-time example.',
        'How does Angular detect the device a user is logged in from?',
        'Difference between prototype and __proto__',
        'How to implement inheritance in JavaScript?',
        'What is Event Delegation?',
        'How to implement role-based access control in Angular?',
        'Why do we need Node.js and npm before working with Angular?',
      ],
    },
    {
      id: 'interview-round',
      icon: 'ti-message-2-question',
      title: 'Interview Round: Live Q&A',
      color: '#A8300B',
      bg: '#FCE9E1',
      questions: [
        'What is the default port of Angular?',
        'How to change the port?',
        'Command to run a project in Angular?',
        'What happens when we run `ng serve`?',
        "What happens if we don't have `AppComponent`?",
        "Is `AppComponent` mandatory? Can't we have our project without `AppComponent`?",
        'Subject vs Observable',
        'How do you communicate between components?',
        'What are other ways other than `@Input` and `@Output`?',
        'Is passing parameters through Angular routing preferred or not?',
        'What is Session Storage?',
        'What can you store in Session Storage?',
        'Can you store personal data in Session Storage?',
        'You have a value that has to be shared across all components. How will you implement this?',
        'Write the syntax/code wherever you implement this',
        'How do you call an API?',
        'What happens if you subscribe to the API in the routing file itself?',
        'Will you be able to see it in the Network tab if you subscribe in the routing file?',
        'Tell me one benefit of subscribing to the API in the routing file instead of the component',
        'What is Change Detection?',
        'How does it work by default?',
        'Where do you implement custom change detection in code?',
        'Can you implement change detection at the routing level?',
        'What happens if you have `**` as the first route in the routing file?',
        'How do you restrict anyone from accessing some URLs or components?',
        'What all Route Guards are there?',
        'What is an Interceptor?',
        'What is an Observable?',
        'What is a Promise?',
        'What is the difference between Promise and Observable?',
        'How do you declare a `BehaviorSubject` and pass one value to all components?',
        'Lifecycle hooks',
        'Does `ngOnChanges` execute every time or only when there are changes? Does it execute before `ngOnInit`?',
        'NgRx',
        'How do you implement lazy loading?',
        'Assume you have a module and component. Write the code in `router.js` to implement this',
        'What are Arrow Functions?',
        'We already have functions. Then why do we need Arrow Functions?',
        'How can you send a payload in an API?',
        'Write code for it',
        'Can you send a payload in a GET API?',
        'Is it recommended?',
        'What are some other API calls?',
        'Difference between PUT and PATCH',
        'In how many ways can we send data through APIs?',
        'What is the toughest issue you faced and how did you resolve it?',
        'Why do we use encapsulation?',
        'What happens when encapsulation is `None`?',
        'What is the default encapsulation?',
        'How can I pass the same styles to child components?',
        'How can you have different styles for one class in such components?',
        'Explain your project',
      ],
    },
    {
      id: 'coding-round',
      icon: 'ti-terminal-2',
      title: 'Coding Round',
      color: '#6B21A8',
      bg: '#F3E8FF',
      questions: [
        'Check if a string is a palindrome',
        'Find duplicate values in an array',
        'Group an array of objects by property',
        'Flatten a nested array',
        'Implement a debounce() function',
        'Find the first non-repeating character in a string',
      ],
    },

    // ─── NODE.JS INTERVIEW QUESTIONS ───────────────────────────────────────────

    {
      id: 'nodejs-fundamentals',
      icon: 'ti-brand-nodejs',
      title: 'Node.js Fundamentals',
      color: '#16A34A',
      bg: '#DCFCE7',
      questions: [
        'What is Node.js and how does it differ from browser JavaScript?',
        'What is the Event Loop in Node.js and how does it work?',
        'What are the phases of the Node.js Event Loop?',
        'What is the difference between process.nextTick() and setImmediate()?',
        'What is the difference between setTimeout() and setImmediate() in the context of the event loop?',
        'How does Node.js handle asynchronous operations if it is single-threaded?',
        'What is the difference between CommonJS (require) and ES Modules (import) in Node.js?',
        'What is module caching in Node.js?',
        'What is libuv and what role does it play in Node.js?',
        'What are Worker Threads in Node.js and when should you use them?',
        'What is the difference between child_process.fork(), spawn(), and exec()?',
        'What is the difference between synchronous and asynchronous code in Node.js?',
      ],
    },
    {
      id: 'nodejs-memory',
      icon: 'ti-cpu',
      title: 'Node.js Memory Management',
      color: '#D97706',
      bg: '#FEF3C7',
      questions: [
        'How does garbage collection work in Node.js?',
        'What is a Buffer in Node.js and when would you use it?',
        'What are common causes of memory leaks in Node.js applications?',
        'How do you detect and diagnose memory leaks in a production Node.js app?',
        'What tools can you use to monitor Node.js memory usage?',
      ],
    },
    {
      id: 'nodejs-clustering',
      icon: 'ti-network',
      title: 'Node.js Clustering & Scaling',
      color: '#0891B2',
      bg: '#E0F2FE',
      questions: [
        'What is clustering in Node.js and why is it needed?',
        'How do you implement clustering in Node.js using the cluster module?',
        'How does the primary process distribute requests among workers in cluster mode?',
        'How do you share state between cluster workers?',
        'What is PM2 and how does it manage Node.js processes?',
      ],
    },
    {
      id: 'nodejs-streams',
      icon: 'ti-waves',
      title: 'Streams & Buffers (Advanced)',
      color: '#0284C7',
      bg: '#E0F2FE',
      questions: [
        'What are the four types of streams in Node.js?',
        'What is backpressure and how does Node.js handle it?',
        'How do you create a custom Transform stream?',
        'What is stream.pipeline() and why is it preferred over .pipe()?',
        'How would you process a large CSV file efficiently in Node.js?',
      ],
    },
    {
      id: 'nodejs-error-handling',
      icon: 'ti-shield-exclamation',
      title: 'Node.js Error Handling',
      color: '#DC2626',
      bg: '#FEE2E2',
      questions: [
        'What is the difference between operational errors and programmer errors?',
        'How do you handle uncaught exceptions in Node.js?',
        'What is the difference between try/catch and process.on("uncaughtException")?',
        'How do you implement graceful shutdown in Node.js?',
        'What is the domain module and is it still recommended?',
      ],
    },
    {
      id: 'nodejs-typescript',
      icon: 'ti-brand-typescript',
      title: 'TypeScript with Node.js',
      color: '#1D4ED8',
      bg: '#DBEAFE',
      questions: [
        'How do you set up TypeScript in a Node.js project?',
        'What are TypeScript decorators and how are they used?',
        'What is the difference between interface and type alias in TypeScript?',
        'What are TypeScript utility types? (Partial, Pick, Omit, Record, Readonly)',
        'What is the difference between unknown and any in TypeScript?',
        'What are generics in TypeScript and how do they improve type safety?',
        'How do you type async functions and Promises in TypeScript?',
        'What is the difference between namespace and module in TypeScript?',
      ],
    },
    {
      id: 'nodejs-microservices',
      icon: 'ti-topology-star',
      title: 'Microservices & Architecture',
      color: '#7C3AED',
      bg: '#EDE9FE',
      questions: [
        'What are microservices and how do they differ from a monolithic architecture?',
        'What are the main advantages and disadvantages of microservices?',
        'How do microservices communicate with each other?',
        'What is an API Gateway and what problems does it solve?',
        'What is the Saga pattern in microservices?',
        'What is the Circuit Breaker pattern?',
        'What is gRPC and when should you use it over REST?',
        'What is the difference between synchronous and asynchronous communication in microservices?',
        'How do you handle distributed transactions in a microservices architecture?',
        'What is the Strangler Fig pattern for migrating from monolith to microservices?',
      ],
    },
    {
      id: 'nodejs-testing',
      icon: 'ti-test-pipe',
      title: 'Node.js Testing',
      color: '#059669',
      bg: '#D1FAE5',
      questions: [
        'What testing frameworks are commonly used in Node.js?',
        'How do you write unit tests for async functions in Jest?',
        'What is the difference between unit, integration, and end-to-end tests?',
        'How do you mock modules and dependencies in Jest?',
        'How do you test Express routes using Supertest?',
        'How do you test asynchronous code in Jest?',
        'What is test coverage and how do you measure it in Node.js?',
        'How do you test for memory leaks in Node.js?',
      ],
    },
    {
      id: 'nodejs-system-design',
      icon: 'ti-sitemap',
      title: 'System Design & Patterns',
      color: '#D97706',
      bg: '#FEF3C7',
      questions: [
        'What are design patterns and which ones are commonly used in Node.js?',
        'What is the Observer pattern and how is it implemented in Node.js?',
        'What is Dependency Injection and how is it used in Node.js?',
        'What is the Repository Pattern?',
        'What is CQRS (Command Query Responsibility Segregation)?',
        'What is Event Sourcing?',
        'How do you design a rate limiter in Node.js?',
        'How do you design a URL shortener service?',
        'How would you design a notification system that sends emails, SMS, and push notifications?',
      ],
    },
    {
      id: 'nodejs-security',
      icon: 'ti-lock',
      title: 'Node.js Security',
      color: '#B91C1C',
      bg: '#FEE2E2',
      questions: [
        'What are the most common security vulnerabilities in Node.js applications?',
        'What is SQL injection and how do you prevent it?',
        'How do you prevent NoSQL injection in MongoDB?',
        'What is JWT and how does authentication work with it?',
        'What is the difference between authentication and authorization?',
        'What is OAuth 2.0 and how does it work?',
        'How do you implement rate limiting in Node.js?',
        'What is helmet.js and what security headers does it set?',
        'How do you store passwords securely in Node.js?',
        'What is CORS and how do you configure it in Node.js?',
      ],
    },
    {
      id: 'nodejs-nosql',
      icon: 'ti-database',
      title: 'NoSQL Databases (MongoDB)',
      color: '#166534',
      bg: '#DCFCE7',
      questions: [
        'What is MongoDB and when would you choose it over a relational database?',
        'What is the difference between embedding and referencing in MongoDB schema design?',
        'What are indexes in MongoDB and when should you create them?',
        'What is sharding in MongoDB?',
        'What is the MongoDB aggregation pipeline?',
        'What is a replica set in MongoDB?',
        'What is the difference between find() and aggregate() in MongoDB?',
        'How do you handle transactions in MongoDB?',
        'What is Mongoose and what are its advantages?',
        'What is the difference between lean() and regular Mongoose queries?',
      ],
    },
    {
      id: 'nodejs-sql',
      icon: 'ti-table',
      title: 'Relational Databases & SQL',
      color: '#1D4ED8',
      bg: '#DBEAFE',
      questions: [
        'What is the difference between SQL and NoSQL databases?',
        'What are indexes in SQL and how do they work?',
        'What is the difference between clustered and non-clustered indexes?',
        'What are SQL joins and when do you use each type?',
        'What are database transaction isolation levels?',
        'What is database normalization? Explain 1NF, 2NF, 3NF',
        'What is the difference between INNER JOIN, LEFT JOIN, and FULL OUTER JOIN?',
        'What is a stored procedure?',
        'What is an ORM? What are the advantages and disadvantages of using one?',
        'What is the N+1 query problem and how do you fix it?',
      ],
    },
    {
      id: 'nodejs-devops',
      icon: 'ti-brand-docker',
      title: 'CI/CD & DevOps',
      color: '#0369A1',
      bg: '#E0F2FE',
      questions: [
        'What is CI/CD and what tools have you used?',
        'What is Docker and how is it used with Node.js?',
        'What is Kubernetes and what problem does it solve?',
        'What is a Dockerfile and how do you write one for Node.js?',
        'What is PM2 and how does it manage Node.js processes?',
        'How do you manage environment variables securely in Node.js?',
        'What is a reverse proxy and why is Nginx used with Node.js?',
        'What are health checks and how do you implement them in Node.js?',
      ],
    },
    {
      id: 'nodejs-performance',
      icon: 'ti-bolt',
      title: 'Performance & Optimization',
      color: '#B45309',
      bg: '#FEF3E2',
      questions: [
        'How do you profile and debug Node.js performance issues?',
        'What is the N+1 query problem and how do you fix it?',
        'What techniques do you use to optimize Node.js application performance?',
        'How does connection pooling work in Node.js database connections?',
        'What is lazy loading and how do you implement it?',
        'How do you implement pagination — offset vs cursor-based?',
        'What is HTTP response compression and how do you enable it?',
        'How do you use worker threads for CPU-intensive tasks?',
      ],
    },
    {
      id: 'nodejs-caching',
      icon: 'ti-database-import',
      title: 'Caching & Redis',
      color: '#DC2626',
      bg: '#FEE2E2',
      questions: [
        'What are common caching strategies? (Cache-Aside, Write-Through, Write-Behind)',
        'What is Redis and what are its use cases in Node.js?',
        'How do you implement a Redis cache in a Node.js application?',
        'What is cache invalidation and what are the strategies?',
        'How do you implement rate limiting using Redis?',
        'What is the difference between Redis Pub/Sub and Redis Streams?',
        'How do you implement distributed locks with Redis?',
        'What is BullMQ and how does it use Redis for job queues?',
      ],
    },
    {
      id: 'nodejs-express-nestjs',
      icon: 'ti-server',
      title: 'Express & NestJS',
      color: '#0F766E',
      bg: '#CCFBF1',
      questions: [
        'How does Express middleware work?',
        'What is NestJS and how does it differ from Express?',
        'What are Guards, Interceptors, and Pipes in NestJS?',
        'How do you implement JWT authentication in NestJS?',
        'What is the difference between app.use() and app.get() in Express?',
        'How do you handle file uploads in Express/NestJS?',
        'How do you implement request validation in NestJS using class-validator?',
        'What is the difference between Fastify and Express?',
        'How do you implement versioned APIs in NestJS?',
      ],
    },
    {
      id: 'nodejs-networking',
      icon: 'ti-wifi',
      title: 'Networking & HTTP',
      color: '#7C3AED',
      bg: '#EDE9FE',
      questions: [
        'What is the difference between HTTP/1.1, HTTP/2, and HTTP/3?',
        'What are WebSockets and how do you implement them in Node.js?',
        'What is CORS and how do you configure it in Node.js?',
        'What is Server-Sent Events (SSE) and when should you use it over WebSockets?',
        'What are HTTP status codes? Explain 2xx, 3xx, 4xx, 5xx ranges.',
        'What is TLS/SSL and how do you enable HTTPS in Node.js?',
        'What is Keep-Alive in HTTP connections?',
        'What is the difference between REST, GraphQL, and gRPC?',
        'How do you implement request timeouts in Node.js HTTP servers?',
      ],
    },
    {
      id: 'nodejs-javascript',
      icon: 'ti-brand-javascript',
      title: 'JavaScript Deep Dive',
      color: '#CA8A04',
      bg: '#FEF9C3',
      questions: [
        'What is the difference between null and undefined in JavaScript?',
        'Explain the JavaScript prototype chain',
        'What is the difference between == and === in JavaScript?',
        'What are closures and how are they used in Node.js?',
        'What is the difference between call(), apply(), and bind()?',
        'What are generator functions and async generators in JavaScript?',
        'What is a Proxy object and how is it used?',
        'What are WeakMap and WeakSet, and why do they allow garbage collection?',
        'What is Promise.all() vs Promise.allSettled() vs Promise.race() vs Promise.any()?',
        'What is the difference between Array.map(), Array.filter(), and Array.reduce()?',
        'Explain event bubbling and event capturing in JavaScript',
        'What is the difference between deep clone and shallow clone?',
      ],
    },
  ];

  getCategories(): Category[] {
    return this.categories;
  }

  getTotalQuestions(): number {
    return this.categories.reduce((acc, cat) => acc + cat.questions.length, 0);
  }
}
